import Image from "next/image";
import Link from "next/link";
import { company } from "../../company";
import { processSteps, solutions } from "../../content";
import { Simulator } from "../forms/LeadForms";
import { SiteLayout } from "../layout/SiteChrome";
import { SolarStory } from "../motion/SolarStory";
import { Arrow, PrimaryCTA, SectionIntro } from "../ui/Elements";

export function HomeView() {
  return <SiteLayout overlayHeader><section className="home-hero"><Image src="/solar-roof.webp" alt="Módulos fotovoltaicos instalados em uma cobertura" fill priority sizes="100vw" /><div className="home-hero__light" aria-hidden="true" /><div className="home-hero__panel" aria-hidden="true">{Array.from({ length: 24 }).map((_, index) => <i key={index} />)}</div><div className="home-hero__content shell"><p className="label">Engenharia solar · {company.serviceRegion}</p><h1>Projeto e instalação de energia solar para seu imóvel.</h1><p>A Aba Sol analisa consumo, estrutura e local para projetar sistemas residenciais, empresariais e rurais.</p><div className="home-hero__actions"><Link className="button button--sun" href="/simulador">Solicitar análise do projeto <Arrow /></Link><Link className="text-link text-link--light" href="/solucoes">Conhecer as soluções <Arrow /></Link></div></div><p className="home-hero__note">Dimensionamento · projeto · instalação · homologação</p></section>
    <section className="value-proof section shell"><div><p className="label">O ponto de partida</p><h2>Antes de falar em resultado, a equipe lê o consumo e o local.</h2></div><div className="value-proof__experience"><strong>40+</strong><span>anos de experiência anterior no setor elétrico</span><p>A origem da Aba Sol está ligada a mais de quatro décadas de atuação no Grupo CPFL Energia, seguida pela criação da empresa com apoio da família e de parceiros.</p><Link className="text-link" href="/sobre">Conhecer a história <Arrow /></Link></div></section>
    <SolarStory />
    <section className="solutions-home section shell"><SectionIntro eyebrow="Tipos de projeto" title="O mesmo sistema exige leituras diferentes." text="Consumo, estrutura e rotina mudam de uma casa para uma empresa ou propriedade rural." /><div className="solutions-home__list">{solutions.map((solution, index) => <article key={solution.slug}><Link className="solutions-home__media" href={`/solucoes/${solution.slug}`}><Image src={solution.image} alt={solution.imageAlt} fill sizes="(max-width: 760px) 100vw, 42vw" /></Link><div><span>0{index + 1}</span><p className="label">{solution.eyebrow}</p><h3>{solution.navLabel}</h3><p>{solution.description}</p><Link className="text-link" href={`/solucoes/${solution.slug}`}>Ver como analisamos <Arrow /></Link></div></article>)}</div></section>
    <section className="home-process section"><div className="shell"><SectionIntro eyebrow="Da conta à conexão" title="Um processo técnico, explicado sem atalhos." /><ol>{processSteps.slice(0, 4).map((step, index) => <li key={step.title}><span>0{index + 1}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol><Link className="button button--outline" href="/como-funciona">Ver todas as etapas <Arrow /></Link></div></section>
    <section className="regional-proof"><div className="regional-proof__photo"><Image src="/solar-detail.webp" alt="Detalhe da superfície e das células de um módulo fotovoltaico" fill sizes="(max-width: 900px) 100vw, 50vw" /></div><div className="regional-proof__copy"><p className="label">Atendimento próximo</p><h2>São José do Rio Preto e região.</h2><p>A análise começa com os dados do imóvel e continua com contato direto para entender a situação de cada projeto.</p><dl><div><dt>Atuação</dt><dd>Residencial, empresarial e rural</dd></div><div><dt>Processo</dt><dd>Projeto, instalação e homologação</dd></div><div><dt>Contato</dt><dd>{company.phoneDisplay}</dd></div></dl></div></section>
    <section className="lead-section section shell"><div className="lead-section__intro"><p className="label">Solicitação inicial</p><h2>Envie as informações básicas do imóvel.</h2><p>A equipe recebe os dados para iniciar a análise. O formulário não calcula economia automaticamente.</p></div><Simulator compact /></section>
    <PrimaryCTA title="Quer conversar sobre o seu imóvel?" />
  </SiteLayout>;
}
